export enum ReportTargetTypeEnum {
  USER = 'USER',
  SERVER = 'SERVER',
  STREAM = 'STREAM',
}

export enum ReportReasonEnum {
  CHILD_SAFETY_EXPLOITATION = 'CHILD_SAFETY_EXPLOITATION',
  HARASSMENT_BULLYING = 'HARASSMENT_BULLYING',
  HATE_SPEECH = 'HATE_SPEECH',
  SEXUAL_CONTENT = 'SEXUAL_CONTENT',
  VIOLENCE_THREATS = 'VIOLENCE_THREATS',
  SELF_HARM = 'SELF_HARM',
  SPAM_SCAM = 'SPAM_SCAM',
  OTHER = 'OTHER',
}

export enum ReportStatusEnum {
  PENDING = 'PENDING',
  INVESTIGATING = 'INVESTIGATING',
  RESOLVED = 'RESOLVED',
  DISMISSED = 'DISMISSED',
}

export enum AuditLogActionEnum {
  SERVER_CREATED = 'SERVER_CREATED',
  STREAM_STARTED = 'STREAM_STARTED',
  MEMBER_MUTED = 'MEMBER_MUTED',
  MEMBER_UNMUTED = 'MEMBER_UNMUTED',
  MEMBER_KICKED = 'MEMBER_KICKED',
  MEMBER_BANNED = 'MEMBER_BANNED',
  MEMBER_UNBANNED = 'MEMBER_UNBANNED',
  REPORT_CREATED = 'REPORT_CREATED',
  REPORT_RESOLVED = 'REPORT_RESOLVED',
  SERVER_SUSPENDED = 'SERVER_SUSPENDED',
  SERVER_UNSUSPENDED = 'SERVER_UNSUSPENDED',
  USER_SUSPENDED = 'USER_SUSPENDED',
  USER_UNSUSPENDED = 'USER_UNSUSPENDED',
}
