export enum ReportTargetTypeEnum {
  USER = 'USER',
  SERVER = 'SERVER',
  STREAM = 'STREAM',
}

export enum ReportReasonEnum {
  CHILD_SAFETY_EXPLOITATION = 'CHILD_SAFETY_EXPLOITATION',
  HARASSMENT_BULLYING = 'HARASSMENT_BULLYING',
  HATE_SPEECH = 'HATE_SPEECH',
  SEXUAL_CONTENT = 'SEXUAL_CONTENT',
  VIOLENCE_THREATS = 'VIOLENCE_THREATS',
  SELF_HARM = 'SELF_HARM',
  SPAM_SCAM = 'SPAM_SCAM',
  OTHER = 'OTHER',
}

export enum ReportStatusEnum {
  PENDING = 'PENDING',
  INVESTIGATING = 'INVESTIGATING',
  RESOLVED = 'RESOLVED',
  DISMISSED = 'DISMISSED',
}
