events {
    worker_connections 1024;
}

http {
    include       mime.types;
    default_type  application/octet-stream;
    
    sendfile        on;
    keepalive_timeout  65;
    
    # ── API (Voxy Backend) ────────────────────────────────────────────────────
    upstream api_servers {
        server api:3000;
    }

    server {
        listen 80;
        listen 443 ssl;
        server_name voxy.d4rkside.com.br;

        ssl_certificate /etc/nginx/certs/cert.pem;
        ssl_certificate_key /etc/nginx/certs/key.pem;
        ssl_protocols TLSv1.2 TLSv1.3;
        ssl_ciphers HIGH:!aNULL:!MD5;

        server_tokens off;
        client_max_body_size 50M;

        location / {
            proxy_pass http://api_servers;
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "upgrade";
            
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
            proxy_cache_bypass $http_upgrade;

            proxy_set_header CF-Connecting-IP $http_cf_connecting_ip;
        }
    }

    # ── LiveKit (Signaling / WebSocket) ───────────────────────────────────────
    upstream livekit_servers {
        server livekit:7880;
    }

    server {
        listen 80;
        listen 443 ssl;
        server_name livekit.d4rkside.com.br;

        ssl_certificate /etc/nginx/certs/cert.pem;
        ssl_certificate_key /etc/nginx/certs/key.pem;
        ssl_protocols TLSv1.2 TLSv1.3;
        ssl_ciphers HIGH:!aNULL:!MD5;

        server_tokens off;

        location / {
            proxy_pass http://livekit_servers;
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "upgrade";
            
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
            proxy_read_timeout 86400; # Impede que o websocket feche por inatividade
        }
    }
}
