name: Deploy Production to Hetzner

on:
  push:
    branches: [ "main" ]

env:
  REGISTRY: ghcr.io

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Set lowercase image name
        run: |
          echo "IMAGE_NAME=$(echo ${{ github.repository }} | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest
          labels: ${{ steps.meta.outputs.labels }}

  deploy-to-hetzner:
    needs: build-and-push-image
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Transfer Compose and Config to Server
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.HETZNER_HOST }}
          username: ${{ secrets.HETZNER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "docker-compose.prod.yml,docker/nginx/nginx.conf"
          target: "~/voxy-production"

      - name: Execute Deploy via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HETZNER_HOST }}
          username: ${{ secrets.HETZNER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            mkdir -p ~/voxy-production
            cd ~/voxy-production
            
            # Cria a pasta de certificados do Nginx e injeta as chaves da Cloudflare
            mkdir -p docker/nginx/certs
            echo "${{ secrets.CF_ORIGIN_CERT }}" > docker/nginx/certs/cert.pem
            echo "${{ secrets.CF_ORIGIN_KEY }}" > docker/nginx/certs/key.pem
            cd ~/voxy-production
            
            echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
            
            cat <<EOF > .env
            DATABASE_URL=${{ secrets.DATABASE_URL }}
            LIVEKIT_API_KEY=${{ secrets.LIVEKIT_API_KEY }}
            LIVEKIT_API_SECRET=${{ secrets.LIVEKIT_API_SECRET }}
            EOF
            
            docker compose -f docker-compose.prod.yml pull api
            docker compose -f docker-compose.prod.yml up -d --remove-orphans
            
            docker image prune -af
